apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: #CHANGE THIS
    env: PROD
  name: #ADD NAME OF PIPELINE
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources:
    requests:
      cpu: 500Mi
      memory: 500M
  runPolicy: SerialLatestOnly
  source:
    git:
      ref: master
      uri: #ADD SOURCE CODE URL HERE
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ci/Jenkinsfile.prod
    type: JenkinsPipeline
